require "user.options"
require "user.keymaps"
require "user.lazy"
require "user.colourscheme"
require "user.cmp"
require "user.lsp"
require "user.treesitter"
require "user.telescope"
require "user.autopairs"
require "user.comment"
require "user.snippets"
require "user.lualine"
require "user.gitsigns"
require "user.nvim_dap"
require "user.todo_comments"
require "user.markdown_preview"

-- additional, unused plugins
-- require "user.toggleterm"
-- require "user.jupynium"
